
set nocompatible

" Temporarily disable filetype detection.
" Apparently some vim plugins want to load with it off.
filetype off

" Do filetype-unfriendly stuff.

" Re-enable filetype and syntax detection.
filetype on
syntax on
set t_Co=256

" Enable the ruler at all times.
set ruler

" Set up 4-space expanded tabs.
set tabstop=4
set shiftwidth=4
set expandtab

" Set up backspacing to work like I expect.
set backspace=indent,eol,start

" Set up Challenger Deep colourscheme.
colorscheme challenger_deep

" Setup haskell-vim.
let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
let g:haskell_backpack = 1                " to enable highlighting of backpack keywords

